Repository High-Coding-org/High-Coding-FE, pull requests merged in 2025-03, with the labels that each got.

#60 주문 완료 페이지 구현
  package-lock.json
  package.json
  src/assets/lottie/truckAnimation.json
  src/pages/OrderComplete/OrderComplete.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/routes/path.ts
Labels: FEAT

#62 키트 주문 페이지 기능 구현
  package-lock.json
  package.json
  src/components/common/Breadcrumb/pathToTitles.ts
  src/constants/delivery.ts
  src/constants/deliveryNotes.ts
  src/constants/paymentMethods.ts
  src/hooks/useDeliveryAddress.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/KitDetailPage/KitDetailPage.tsx
  src/pages/KitOrderPage/KitOrderPage.tsx
  src/pages/KitOrderPage/OrderCoupon/OrderCoupon.tsx
  src/pages/KitOrderPage/OrderItem/OrderItem.tsx
  src/pages/KitOrderPage/PaymentMethod/PaymentMethod.tsx
  src/pages/KitOrderPage/PriceInfo/PriceInfo.tsx
  src/pages/KitOrderPage/ShippingInfo/DeliveryNote.tsx
  src/pages/KitOrderPage/ShippingInfo/DetailedAddress.tsx
  src/pages/KitOrderPage/ShippingInfo/RegionalAddress.tsx
  src/pages/KitOrderPage/ShippingInfo/ShippingInfo.tsx
  src/pages/KitOrderPage/ShippingInfo/ShippingUser.tsx
  src/pages/KitOrderPage/components/SectionContainer.tsx
  src/pages/KitOrderPage/constants/submitErrorMessage.ts
  src/pages/KitOrderPage/type.ts
  src/pages/OrderPage/OrderPage.tsx
  src/pages/PurchasePage/PurchasePage.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/routes/path.ts
  src/utils/.gitkeep
  src/utils/formatMoneyKR.ts
  src/utils/formatPhoneNumber.ts
Labels: FEAT

#66 로고 깨짐 에러 픽스
  src/components/common/Logo/Logo.tsx
Labels: FIX

#64 헤더 컴포넌트 수정
  src/components/common/Header/Header.tsx
  src/constants/header.ts
  src/pages/CustomerCenter/CustomerCenter.tsx
  src/pages/MyPlantPage/PlantDictionary/PlantDictionary.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: FEAT, FIX

#72 DetailPage API 연결
  src/hooks/api/useKit.ts
  src/pages/KitDetailPage/KitDetailPage.tsx
  src/services/apiEndpoint.ts
  src/services/axiosInstance.ts
  src/services/kitDetail/getKitDetail.ts
  src/types/KitDetail/kitDetail.ts
Labels: FEAT

#76 주문 목록 페이지 구현
  src/pages/OrderList/OrderData.tsx
  src/pages/OrderList/OrderList.tsx
  src/pages/OrderList/type.ts
  src/pages/ProfilePage/OrderList/OrderList.tsx
  src/pages/index.ts
  src/services/apiEndpoint.ts
  src/utils/formatDate.ts
Labels: FEAT

#58 회원정보 페이지, 비밀번호 변경 페이지 구현
  src/components/common/Breadcrumb/BreadcrumbAndTitle.tsx
  src/components/common/Breadcrumb/pathToTitles.ts
  src/constants/profileDataKey.ts
  src/hooks/api/usePasswordChange.ts
  src/hooks/api/useProfile.ts
  src/pages/EditProfilePage/AddressField.tsx
  src/pages/EditProfilePage/FieldInput.tsx
  src/pages/EditProfilePage/ProfileEdit.tsx
  src/pages/EditProfilePage/profileFormFields.ts
  src/pages/LoginPage/LoginForm/SignUpForm.tsx
  src/pages/OrderList/OrderList.tsx
  src/pages/PasswordChangePage/PasswordChangePage.tsx
  src/pages/PasswordChangePage/PasswordFormField.tsx
  src/pages/PasswordChangePage/PasswordInput.tsx
  src/pages/PasswordChangePage/passwordSchema.ts
  src/pages/PasswordChangePage/type.ts
  src/pages/ProfilePage/MyPage.tsx
  src/pages/ProfilePage/NoProfileData.tsx
  src/pages/ProfilePage/ProfileItem.tsx
  src/pages/ProfilePage/ProfileList.tsx
  src/pages/ProfilePage/ProfilePage.tsx
  src/pages/ProfilePage/type.ts
  src/pages/index.ts
  src/routes/index.tsx
  src/routes/path.ts
  src/services/apiEndpoint.ts
  src/services/passwordChange/changePassword.ts
  src/services/profile/getProfile.ts
Labels: FEAT

#79 Error fix dev branch
  src/pages/OrderList/OrderList.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/services/apiEndpoint.ts
  src/services/orderList/getOrderList.ts
Labels: FIX

#59 AI 식물 추천 페이지 UI 구현
  package-lock.json
  package.json
  src/assets/lottie/plantAnimation.json
  src/pages/MyPlantPage/AIRecommend/AIRecommend.tsx
  src/pages/MyPlantPage/AIRecommend/PreResultContainer/PreResultContainer.tsx
  src/pages/MyPlantPage/AIRecommend/SliderContainer/PageIndicator.tsx
  src/pages/MyPlantPage/AIRecommend/SliderContainer/PageTitle.tsx
  src/pages/MyPlantPage/AIRecommend/SliderContainer/PlantGraph/GraphDefaultOptions.ts
  src/pages/MyPlantPage/AIRecommend/SliderContainer/PlantGraph/GraphLegend.tsx
  src/pages/MyPlantPage/AIRecommend/SliderContainer/PlantGraph/PlantGraph.tsx
  src/pages/MyPlantPage/AIRecommend/SliderContainer/PlantImage/PlantImage.tsx
  src/pages/MyPlantPage/AIRecommend/SliderContainer/PlantName/PlantName.tsx
  src/pages/MyPlantPage/AIRecommend/SliderContainer/SliderContainer.tsx
  src/pages/MyPlantPage/AIRecommend/components/InputField.tsx
  src/pages/MyPlantPage/AIRecommend/constants/titles.ts
  src/pages/MyPlantPage/AIRecommend/type.ts
  src/pages/MyPlantPage/PlantRecommend/PlantRecommend.tsx
  src/pages/index.ts
Labels: DESIGN

#82 마이페이지의 sidebar 수정
  src/components/common/SideBar.tsx
  src/components/common/SideBar/SideBar.tsx
  src/components/common/SideBar/menuItems.ts
  src/pages/OrderList/OrderList.tsx
  src/pages/PasswordChangePage/PasswordChangePage.tsx
  src/pages/ProfilePage/ProfilePage.tsx
Labels: REFACTOR

#86 나의 식물 목록 페이지 ui 구현
  package-lock.json
  package.json
  src/components/common/Breadcrumb/pathToTitles.ts
  src/components/ui/dropdown-menu.tsx
  src/pages/MyPlantPage/MyPlantPage.tsx
  src/pages/MyPlantPage/MyPlantPage/AddPlantCard.tsx
  src/pages/MyPlantPage/MyPlantPage/MyPlantPage.tsx
  src/pages/MyPlantPage/MyPlantPage/PlantCard.tsx
  src/pages/MyPlantPage/MyPlantPage/PlantDropdownMenu.tsx
  src/pages/MyPlantPage/MyPlantPage/type.ts
  src/pages/index.ts
Labels: DESIGN

#89 토큰 유효성 검사 기능 구현
  src/pages/Layout/Layout.tsx
  src/pages/LoginPage/AuthOverlay.tsx
  src/pages/LoginPage/LoginForm/SignInForm.tsx
  src/pages/LoginPage/LoginForm/SignUpForm.tsx
  src/pages/LoginPage/components/CustomFormField.tsx
  src/services/apiEndpoint.ts
  src/services/auth/signIn.ts
  src/services/auth/signUp.ts
  src/services/auth/tokenValid.ts
  src/types/auth/auth.ts
  src/types/auth/tokenValid.ts
Labels: FEAT

#91 src/pages 하위 폴더 정리
  src/pages/Kit/KitDetailPage/KitDetailPage.tsx
  src/pages/Kit/KitDetailPage/NoKitData.tsx
  src/pages/Kit/KitDetailPage/StarRating.tsx
  src/pages/Kit/KitDetailPage/type.ts
  src/pages/Kit/KitOrderPage/KitOrderPage.tsx
  src/pages/Kit/KitOrderPage/OrderCoupon/OrderCoupon.tsx
  src/pages/Kit/KitOrderPage/OrderItem/OrderItem.tsx
  src/pages/Kit/KitOrderPage/PaymentMethod/PaymentMethod.tsx
  src/pages/Kit/KitOrderPage/PriceInfo/PriceInfo.tsx
  src/pages/Kit/KitOrderPage/ShippingInfo/DeliveryNote.tsx
  src/pages/Kit/KitOrderPage/ShippingInfo/DetailedAddress.tsx
  src/pages/Kit/KitOrderPage/ShippingInfo/RegionalAddress.tsx
  src/pages/Kit/KitOrderPage/ShippingInfo/ShippingInfo.tsx
  src/pages/Kit/KitOrderPage/ShippingInfo/ShippingUser.tsx
  src/pages/Kit/KitOrderPage/components/SectionContainer.tsx
  src/pages/Kit/KitOrderPage/constants/submitErrorMessage.ts
  src/pages/Kit/KitOrderPage/type.ts
  src/pages/Kit/OrderComplete/OrderComplete.tsx
  src/pages/MyPage/OrderList/OrderData.tsx
  src/pages/MyPage/OrderList/OrderList.tsx
  src/pages/MyPage/OrderList/type.ts
  src/pages/MyPage/PasswordChangePage/PasswordChangePage.tsx
  src/pages/MyPage/PasswordChangePage/PasswordFormField.tsx
  src/pages/MyPage/PasswordChangePage/PasswordInput.tsx
  src/pages/MyPage/PasswordChangePage/passwordSchema.ts
  src/pages/MyPage/PasswordChangePage/type.ts
  src/pages/MyPage/ProfilePage/NoProfileData.tsx
  src/pages/MyPage/ProfilePage/ProfileItem.tsx
  src/pages/MyPage/ProfilePage/ProfileList.tsx
  src/pages/MyPage/ProfilePage/ProfilePage.tsx
  src/pages/MyPage/ProfilePage/type.ts
  src/pages/Plant/AIRecommend/AIRecommend.tsx
  src/pages/Plant/AIRecommend/PreResultContainer/PreResultContainer.tsx
  src/pages/Plant/AIRecommend/SliderContainer/PageIndicator.tsx
  src/pages/Plant/AIRecommend/SliderContainer/PageTitle.tsx
  src/pages/Plant/AIRecommend/SliderContainer/PlantGraph/GraphDefaultOptions.ts
  src/pages/Plant/AIRecommend/SliderContainer/PlantGraph/GraphLegend.tsx
  src/pages/Plant/AIRecommend/SliderContainer/PlantGraph/PlantGraph.tsx
  src/pages/Plant/AIRecommend/SliderContainer/PlantImage/PlantImage.tsx
  src/pages/Plant/AIRecommend/SliderContainer/PlantName/PlantName.tsx
  src/pages/Plant/AIRecommend/SliderContainer/SliderContainer.tsx
  src/pages/Plant/AIRecommend/components/InputField.tsx
  src/pages/Plant/AIRecommend/constants/titles.ts
  src/pages/Plant/AIRecommend/type.ts
  src/pages/Plant/MyPlantPage/AddPlantCard.tsx
  src/pages/Plant/MyPlantPage/MyPlantPage.tsx
  src/pages/Plant/MyPlantPage/PlantCard.tsx
  src/pages/Plant/MyPlantPage/PlantDropdownMenu.tsx
  src/pages/Plant/MyPlantPage/type.ts
  src/pages/Plant/PlantDetail/PlantDetail.tsx
  src/pages/Plant/PlantDictionary/PlantDictionary.tsx
  src/pages/Plant/PlantRegister/PlantRegister.tsx
  src/pages/PurchaseHistoryPage/PurchaseHistoryPage.tsx
  src/pages/PurchaseHistoryPage/type.ts
  src/pages/index.ts
  src/routes/index.tsx
Labels: RENAME
