Repository High-Coding-org/High-Coding-FE, pull requests merged in 2025-01, with the labels that each got.

#19 [✨feat]: 로그인 페이지 UI 구현
  .gitignore
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/assets/.gitkeep
  src/assets/social/btn_google.svg
  src/assets/social/btn_kakao.svg
  src/assets/social/btn_naver.svg
  src/components/common/DatePicker/DatePicker.tsx
  src/components/ui/calendar.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/popover.tsx
  src/components/ui/select.tsx
  src/constants/.gitkeep
  src/constants/formValidation.ts
  src/constants/localStorageKey.ts
  src/constants/socialLogos.ts
  src/hooks/.gitkeep
  src/hooks/api/useAuth.ts
  src/hooks/useLocalStorage.ts
  src/lib/utils.ts
  src/main.tsx
  src/pages/.gitkeep
  src/pages/LoginPage/AuthOverlay.tsx
  src/pages/LoginPage/LoginForm/SignInForm.tsx
  src/pages/LoginPage/LoginForm/SignUpForm.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/components/CustomFormField.tsx
  src/services/.gitkeep
  src/services/apiEndpoint.ts
  src/services/auth/signIn.ts
  src/services/auth/signUp.ts
  src/services/axiosInstance.ts
  src/types/.gitkeep
  src/types/api.ts
  src/types/auth.ts
  src/vite-env.d.ts
  svg.d.ts
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: FEAT

#23 [🐛fix]: 경로파라미터 사용 시에도 제목과 브래드크럼 정확하게 나오게 수정
  src/components/common/Breadcrumb.tsx
Labels: FIX

#27 [✨feat]: 페이지 라우팅 기능 구현
  src/App.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/MyPlantPage/MyPlantPage.tsx
  src/pages/MyPlantPage/PlantDetail/PlantDetail.tsx
  src/pages/MyPlantPage/PlantRecommend/PlantRecommend.tsx
  src/pages/MyPlantPage/PlantRegister/PlantRegister.tsx
  src/pages/NotFoundPage/NotFoundPage.tsx
  src/pages/ProductPage/ProductPage.tsx
  src/pages/ProfilePage/MyPage.tsx
  src/pages/ProfilePage/OrderList/OrderList.tsx
  src/pages/PurchasePage/PurchasePage.tsx
  src/pages/index.ts
  src/routes/BreadcrumbTitle.ts
  src/routes/index.tsx
  src/routes/path.ts
  src/types/path.ts
Labels: FEAT

#22 [🎨design]: header에 bottomNavbar 메뉴 추가
  src/components/common/Header.tsx
  src/components/common/Header/Header.tsx
  src/constants/header.ts
Labels: DESIGN

#29 [✨feat]: 404 페이지 구현
  src/pages/NotFoundPage/NotFoundPage.tsx
Labels: FEAT

#33 [✨feat]: 키트상세페이지 UI 구현
  src/pages/KitDetailPage/KitDetailPage.tsx
  src/pages/KitDetailPage/StarRating.tsx
  src/pages/KitDetailPage/type.ts
Labels: FEAT

#37 [✨feat]: 홈 페이지 구현
  package-lock.json
  package.json
  src/assets/HomeBackground/HomeBackground.png
  src/index.css
  src/pages/HomePage/HomePage.tsx
  src/pages/HomePage/bounceAnimation.css
  src/pages/HomePage/components/ResponsiveText.tsx
  src/pages/HomePage/constants.ts
  tailwind.config.js
Labels: FEAT

#31 [✨feat]:회원정보 수정 페이지 UI 구현
  src/pages/EditProfilePage/AddressField.tsx
  src/pages/EditProfilePage/FieldInput.tsx
  src/pages/EditProfilePage/ProfileEdit.tsx
  src/pages/EditProfilePage/profileFormFields.ts
Labels: FEAT

#35 [✨feat]: 키트 구매내역 페이지 UI 구현
  src/pages/PurchaseHistoryPage/PurchaseHistoryPage.tsx
  src/pages/PurchaseHistoryPage/type.ts
Labels: FEAT

#39 [✨feat]: 페이지 레이아웃 구현
  src/pages/Layout/Layout.tsx
  src/routes/CheckUserLogin.tsx
  src/routes/PrivateRoute.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: FEAT

#41 [🐛fix]: dev 브랜치 오류 해결
  src/pages/HomePage/HomePage.tsx
  src/pages/Layout/Layout.tsx
Labels: FIX

#43 [♻️refactor]: 로고 공통 컴포넌트화 및 헤더 컴포넌트 간단한 기능 추가
  src/components/common/Header/Header.tsx
  src/components/common/Logo/Logo.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/Layout/Layout.tsx
  src/pages/LoginPage/AuthOverlay.tsx
  tailwind.config.js
Labels: FEAT, REFACTOR

#48 [🎨design]: 소수점 단위로 별이 표현될 수 있도록 변경
  src/pages/KitDetailPage/StarRating.tsx
Labels: DESIGN

#49 [✨feat]: kit detail 페이지 api 연동
  package-lock.json
  package.json
  src/components/common/Spinner/Spinner.tsx
  src/components/common/ToastProvider/ToastProvider.tsx
  src/constants/kitId.ts
  src/main.tsx
  src/pages/HomePage/HomePage.tsx
  src/pages/KitDetailPage/KitDetailPage.tsx
  src/pages/KitDetailPage/NoKitData.tsx
  src/pages/KitDetailPage/StarRating.tsx
  src/pages/KitDetailPage/type.ts
  src/pages/KitDetailPage/useKit.ts
  src/pages/ProductPage/ProductPage.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/services/apiEndpoint.ts
  src/services/kitDetail/getKitDetail.ts
  src/store/.gitkeep
  src/store/kitDetailErrorStore.ts
  src/types/KitDetail/kitDetail.ts
  src/types/store/kitDetailError.ts
  tailwind.config.js
Labels: FEAT
