Repository High-Coding-org/High-Coding-FE, pull requests merged in 2025-04, with the labels that each got.

#96 회원 정보 페이지 수정
  src/pages/HomePage/HomePage.tsx
  src/pages/Kit/KitDetailPage/KitDetailPage.tsx
  src/pages/MyPage/ProfilePage/ProfileList.tsx
  src/pages/MyPage/ProfilePage/ProfilePage.tsx
  src/pages/MyPage/ProfilePage/type.ts
  src/store/globalErrorStore.ts
  src/store/kitDetailErrorStore.ts
  src/types/store/globalError.ts
  src/types/store/kitDetailError.ts
Labels: REFACTOR

#101 로그인 페이지 에러 픽스
  src/hooks/api/useAuth.ts
Labels: FIX

#102 식물 등록 페이지 UI 구현
  src/pages/Plant/PlantRegister/GoalGrowthField.tsx
  src/pages/Plant/PlantRegister/ImageDropZone.tsx
  src/pages/Plant/PlantRegister/ImagePreview.tsx
  src/pages/Plant/PlantRegister/InputField.tsx
  src/pages/Plant/PlantRegister/PlantRegister.tsx
  src/pages/Plant/PlantRegister/constants/inputFields.ts
  src/pages/Plant/PlantRegister/constants/validExtensions.ts
  src/pages/Plant/PlantRegister/types.ts
Labels: DESIGN

#100 식물 성장 일기 페이지의 디자인 구현
  package-lock.json
  package.json
  src/components/common/Breadcrumb/BreadcrumbAndTitle.tsx
  src/components/common/Breadcrumb/pathToTitles.ts
  src/components/common/DatePicker/DatePicker.tsx
  src/components/ui/carousel.tsx
  src/components/ui/progress.tsx
  src/components/ui/textarea.tsx
  src/pages/Plant/PlantDiary/DiaryVisualization/DiaryVisualization.tsx
  src/pages/Plant/PlantDiary/PlantDiary.tsx
  src/pages/Plant/PlantDiary/PlantDiaryForm/PlantDiaryForm.tsx
  src/pages/Plant/PlantDiary/PlantDiaryForm/PlantInfo.tsx
  src/pages/Plant/PlantDiary/components/PlantCalendar.tsx
  src/pages/Plant/PlantDiary/components/PlantGraph.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/routes/path.ts
Labels: DESIGN

#104 plantRegister페이지 파일 확장자 webp도 업로드 가능하도록 수정
  src/pages/Plant/PlantRegister/ImageDropZone.tsx
  src/pages/Plant/PlantRegister/PlantRegister.tsx
  src/pages/Plant/PlantRegister/constants/validExtensions.ts
Labels: DESIGN

#106 식물 라우팅 수정
  src/constants/header.ts
  src/pages/Plant/PlantDetail/PlantDetail.tsx
  src/pages/index.ts
  src/routes/index.tsx
  src/routes/path.ts
Labels: RENAME
